// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jamestunnell/topdown/engine (interfaces: Mode)

// Package mock_engine is a generated GoMock package.
package mock_engine

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	ebiten "github.com/hajimehoshi/ebiten/v2"
	topdown "github.com/jamestunnell/topdown"
	engine "github.com/jamestunnell/topdown/engine"
	resource "github.com/jamestunnell/topdown/resource"
)

// MockMode is a mock of Mode interface.
type MockMode struct {
	ctrl     *gomock.Controller
	recorder *MockModeMockRecorder
}

// MockModeMockRecorder is the mock recorder for MockMode.
type MockModeMockRecorder struct {
	mock *MockMode
}

// NewMockMode creates a new mock instance.
func NewMockMode(ctrl *gomock.Controller) *MockMode {
	mock := &MockMode{ctrl: ctrl}
	mock.recorder = &MockModeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMode) EXPECT() *MockModeMockRecorder {
	return m.recorder
}

// Draw mocks base method.
func (m *MockMode) Draw(arg0 *ebiten.Image) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Draw", arg0)
}

// Draw indicates an expected call of Draw.
func (mr *MockModeMockRecorder) Draw(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Draw", reflect.TypeOf((*MockMode)(nil).Draw), arg0)
}

// Initialize mocks base method.
func (m *MockMode) Initialize(arg0 topdown.Size[int], arg1 resource.Manager) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initialize", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Initialize indicates an expected call of Initialize.
func (mr *MockModeMockRecorder) Initialize(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialize", reflect.TypeOf((*MockMode)(nil).Initialize), arg0, arg1)
}

// Layout mocks base method.
func (m *MockMode) Layout(arg0, arg1 int) (int, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Layout", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	return ret0, ret1
}

// Layout indicates an expected call of Layout.
func (mr *MockModeMockRecorder) Layout(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Layout", reflect.TypeOf((*MockMode)(nil).Layout), arg0, arg1)
}

// Update mocks base method.
func (m *MockMode) Update() (engine.Mode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update")
	ret0, _ := ret[0].(engine.Mode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockModeMockRecorder) Update() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMode)(nil).Update))
}
